In [1]:
import numpy as np

In [2]:
sigma_x = np.array([[ 0, 1 ],
                    [ 1, 0 ]])

sigma_y = np.array([[ 0 ,-1j],
                    [ 1j, 0 ]])

sigma_z = np.array([[ 1 , 0 ],
                    [ 0 ,-1 ]])

In [4]:
sigma_x@sigma_y == 1j*sigma_z

array([[ True,  True],
       [ True,  True]])

In [15]:
sigma_z@sigma_x == 1j*sigma_y

array([[ True,  True],
       [ True,  True]])

In [14]:
sigma_y@sigma_z == 1j*sigma_x

array([[ True,  True],
       [ True,  True]])